#!/bin/bash

source app/functions

# Set database connection

function databaseCredentials() {
    databaseHost

    databaseName

    databaseUser

    databasePassword

    databasePrefix

    mysql -h $DATABASE_HOST -u $DATABASE_USER -p$DATABASE_PASSWORD $DATABASE_NAME -e "SELECT * FROM ${DATABASE_PREFIX}configuration LIMIT 1"

    if [[ $? != 0 ]]; then
        warning "Could not connect to the database"
        
        databaseCredentials
    else
        echo "DATABASE_HOST=$DATABASE_HOST" >> .env
        echo "DATABASE_USER=$DATABASE_USER" >> .env
        echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
        echo "DATABASE_NAME=$DATABASE_NAME" >> .env
        echo "DATABASE_PREFIX=$DATABASE_PREFIX" >> .env

        success "Database "
    fi
}
