#!/bin/bash

source app/functions

# Database user question

function databaseUser() {

    DATABASE_USER_DEFAULT=$(detectDatabaseParam '_DB_USER_')

    echo -n "What is the database user? [$DATABASE_USER_DEFAULT] "
    read DATABASE_USER
    DATABASE_USER=${DATABASE_USER:-$DATABASE_USER_DEFAULT}
}
