#!/bin/bash

source app/functions

# Database host question

function databaseHost() {

    DATABASE_HOST_DEFAULT=$(detectDatabaseParam '_DB_SERVER_')

    echo -n "What is the database host? [$DATABASE_HOST_DEFAULT] "
    read DATABASE_HOST
    DATABASE_HOST=${DATABASE_HOST:-$DATABASE_HOST_DEFAULT}
}
