#!/bin/bash

source app/functions

# Database prefix question

function databasePrefix() {    

    DATABASE_PREFIX_DEFAULT=$(detectDatabaseParam '_DB_PREFIX_')

    echo -n "What is the database prefix? [$DATABASE_PREFIX_DEFAULT] "
    read DATABASE_PREFIX
    DATABASE_PREFIX=${DATABASE_PREFIX:-$DATABASE_PREFIX_DEFAULT}
}
