#!/bin/bash

source app/functions

# Database password question
function databasePassword() {
    DATABASE_PASSWORD_DEFAULT=$(detectDatabaseParam '_DB_PASSWD_')

    if [ ${#DATABASE_PASSWORD_DEFAULT} -gt 1 ]; then
        MASKED_DEFAULT="${DATABASE_PASSWORD_DEFAULT:0:1}$(echo "${DATABASE_PASSWORD_DEFAULT:1:${#DATABASE_PASSWORD_DEFAULT}-2}" | sed 's/./*/g')${DATABASE_PASSWORD_DEFAULT: -1}"
    else
        MASKED_DEFAULT="$DATABASE_PASSWORD_DEFAULT"
    fi

    echo -n "What is the database password? [$MASKED_DEFAULT] "

    read -r -s DATABASE_PASSWORD

    echo ""

    DATABASE_PASSWORD=${DATABASE_PASSWORD:-$DATABASE_PASSWORD_DEFAULT}
}