#!/bin/bash

source app/functions

# Set database connection

function databaseCredentials() {
    databaseHost

    databaseName

    databaseUser

    databasePassword

    databasePrefix

    mysql -h $DATABASE_HOST -u $DATABASE_USER -p$DATABASE_PASSWORD $DATABASE_NAME -e "SELECT count(*) FROM ${DATABASE_PREFIX}configuration LIMIT 1" > /dev/null

    if [[ $? != 0 ]]; then
        warning "Could not connect to the database"
        
        databaseCredentials
    else
        echo "DATABASE_HOST=$DATABASE_HOST" >> .juice_setup
        echo "DATABASE_USER=$DATABASE_USER" >> .juice_setup
        echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .juice_setup
        echo "DATABASE_NAME=$DATABASE_NAME" >> .juice_setup
        echo "DATABASE_PREFIX=$DATABASE_PREFIX" >> .juice_setup

        success "Database successfully connected"
    fi
}
