#!/bin/bash

source app/functions

# Database name question

function databaseName() {

    DATABASE_NAME_DEFAULT=$(detectDatabaseParam '_DB_NAME_')

    echo -n "What is the database name? [$DATABASE_NAME_DEFAULT] "
    read DATABASE_NAME
    DATABASE_NAME=${DATABASE_NAME:-$DATABASE_NAME_DEFAULT}
}
