#!/bin/bash

source app/functions

# Database password question

function databasePassword() {

    DATABASE_PASSWORD_DEFAULT=$(detectDatabaseParam '_DB_PASSWD_')

    echo -n "What is the database password? [$DATABASE_PASSWORD_DEFAULT] "
    read -s DATABASE_PASSWORD
    DATABASE_PASSWORD=${DATABASE_PASSWORD:-$DATABASE_PASSWORD_DEFAULT}
}
