#!/bin/bash

source app/functions

# Detect a database parameter automatically

function detectDatabaseParam() {

    DATABASE_PARAM=$(php -r "include('$APPLICATION_PATH/config/config.inc.php'); echo $1;")

    if [[ $? != 0 ]]; then
        echo ""  # Echo empty string if PHP command failed
    else
        echo $DATABASE_PARAM
    fi
}
