#!/bin/bash

source app/functions

if [[ -f .juice_setup ]]; then
    source .juice_setup
else
    info "Starting a new configuration"
fi


function publicUrl() {
    SHOP_URL_DEFAULT=$(mysql -h"$DATABASE_HOST" -u"$DATABASE_USER" -p"$DATABASE_PASSWORD" "$DATABASE_NAME" -se "SELECT su.domain FROM ${DATABASE_PREFIX}shop_url su JOIN ${DATABASE_PREFIX}shop s ON su.id_shop=s.id_shop WHERE s.active = 1 AND su.main = 1 LIMIT 1")
    
    echo -n "What is shop URL? [$SHOP_URL_DEFAULT] "
    read -r SHOP_URL
    SHOP_URL=${SHOP_URL:-$SHOP_URL_DEFAULT}
    echo "SHOP_URL=$SHOP_URL" >> .juice_setup

    http_code=$(curl -o /dev/null -s -w "%{http_code}\n" "$SHOP_URL")
    if [[ $http_code -lt 200 || $http_code -ge 400 ]]; then
        warning "The URL provides a response code is outside of the 2xx and 3xx range: $http_code"
        publicUrl
    else
        success "The URL provides a response code is within the 2xx or 3xx range: $http_code"
    fi
}

