#!/bin/bash

source app/functions

# Set the default application path

function useCustomUpgradeHooks() {

    echo -n "Do you want run project specific scripts before and after upgrade? [yes/no, default no] "
    read CUSTOM_HOOKS

    if [[ $CUSTOM_HOOKS == "yes" && $APPLICATION_PATH && $PRESTASHOP_NEW_VERSION ]]; then
        
        # Create the custom hooks
        echo "#!bin/bash\n" > "$APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-before"
        if [[ $? -eq 0 ]]; then
            success "empty script $APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-before is created."
        else
            echo $?
        fi

        echo "#!bin/bash\n" > "$APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-after"
        if [[ $? -eq 0 ]]; then
            success "empty script $APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-after is created."
        else
            echo $?
        fi
    else
        info "Custom hooks ignored."
    fi

}
