#!/bin/bash

source app/functions
source .juice_setup

if [[ $CUSTOM_HOOKS == "yes" && $APPLICATION_PATH && $PRESTASHOP_NEW_VERSION ]]; then
    
    # Create the custom hooks
    cp config/blank-custom-hook-script "$APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-before"
    if [[ $? -eq 0 ]]; then
        success "empty script $APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-before is created."
    else
        echo $?
    fi

    cp config/blank-custom-hook-script "$APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-after"
    if [[ $? -eq 0 ]]; then
        success "empty script $APPLICATION_PATH/blauwfruit-juice-upgrade-$PRESTASHOP_NEW_VERSION-hook-after is created."
    else
        echo $?
    fi
else
    info "Custom hooks ignored."
fi
