#!/bin/bash

source app/functions

source .juice_setup

success "Starting the purge process."

# SQL statement to truncate specified tables
SQL="TRUNCATE TABLE ${DATABASE_PREFIX}connections; TRUNCATE TABLE ${DATABASE_PREFIX}connections_source; TRUNCATE TABLE ${DATABASE_PREFIX}guest; TRUNCATE TABLE ${DATABASE_PREFIX}log;"

# Execute the SQL statement
echo $SQL | mysql -h$DATABASE_HOST -u$DATABASE_USER -p$DATABASE_PASSWORD $DATABASE_NAME

# Check if the MySQL command was successful
if [[ $? == 0 ]]; then
    success "Database tables purged successfully."
else
    danger "Failed to purge database tables."
    exit 1
fi

success "Purge process completed successfully."