#!/bin/bash

source .juice_setup
source app/constants
source app/functions

# Process

success "Start restore process"

mkdir -p $BACKUP_PATH

if [ $(php -r "include('${APPLICATION_PATH}/config/config.inc.php');echo _PS_VERSION_;") == $PRESTASHOP_OLD_VERSION ]; then
    warning "You are restoring a backup while your current appliation is not upgraded."

    echo -n "Are you sure you want to continue? [yes/no] "
        
    read RESTORE_ANYWAYS

    if [[ $RESTORE_ANYWAYS == 'no' ]]; then
        info "Restoring process is cancelled.";
        exit 1;
    fi
fi

mysql -h"$DATABASE_HOST" -u"$DATABASE_USER" -p"$DATABASE_PASSWORD" "$DATABASE_NAME" < "$BACKUP_PATH/database.sql"

if [[ $? == 0 ]]; then
    success "Database restored"
else
    warning "mysql import went wrong giving exit code $?"
fi

rsync -alv --delete \
    --exclude '/img' \
    --exclude '/download' \
    --exclude '/upload' \
    $BACKUP_PATH/files/ $APPLICATION_PATH

if [ $? == 0 ]; then
    success "rsync was success fully completed"
else
    warning "rsync went wrong giving exit code $?"
fi

rm -rf "$APPLICATION_PATH/cache/smarty/compile" \
    "$APPLICATION_PATH/cache/class_index.php" \
    "$APPLICATION_PATH/var/"

rm -rf "$APPLICATION_PATH/cache/smarty/compile" \
       "$APPLICATION_PATH/cache/cachefs" \
       "$APPLICATION_PATH/cache/class_index.php" \
       "$APPLICATION_PATH/var/cache/"

if [[ $? == 0 ]]; then
    success "Remove cache files completed"
else
    warming "Remove cache files could not be completed"
fi

success "Dest folder restored"