#!/bin/bash

# Install necessary packages (rsync, git) if not installed
if ! command -v rsync &> /dev/null; then
  echo "rsync is not installed, installing..."
  apt-get update && apt-get install -y git rsync
  if [[ $? -ne 0 ]]; then
    echo "Failed to install rsync. Exiting."
    exit 1
  fi
else
  echo "rsync is already installed."
fi

source app/functions

# Include all the questions

while IFS= read -r file; do
    if [[ $file != 'app/setup' ]]; then
        source "$file"
    fi
done < <(find app/setup)

# Setup questions


newsetup

applicationPath

databaseCredentials

publicUrl

currentVersion

newVersion

autoupgradeVersion

customThemeFolder

backofficeFolder

success "You're all setup now, you can start the backup and upgrade process. Run juice/backup then juice/upgrade"