#!/bin/bash

source app/functions

# Include all the questions

while IFS= read -r file; do
    if [[ $file != 'app/setup' ]]; then
        source "$file"
    fi
done < <(find app/setup)

# Setup questions


newsetup

applicationPath

databaseCredentials

publicUrl

currentVersion

newVersion

customThemeFolder

backofficeFolder

success "You're all setup now, you can start the backup and upgrade process. Run juice/backup then juice/upgrade"